services:
  market_backend:
    build:
      context: ../ActusMarket/server
    env_file:
      - ../ActusMarket/server/.env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    

    
  go_backend:
    build:
      context: ../ActusGo/backend
    env_file:
      - ../ActusGo/backend/.env
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}

networks:
  default:
    driver: bridge