import Image1 from '../../components/Images/SuccessCompo.png';
import Image2 from '../../components/Images/1.jpg';

export const products = [
  {
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 1,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 53,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 30,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
];
