import Image1 from '../../components/Images/SuccessCompo.png';
import Image2 from '../../components/Images/1.jpg';
import Image3 from '../../components/Images/2.jpg';
import Image4 from '../../components/Images/3.jpg';
import Image5 from '../../components/Images/4.jpg';
import Image6 from '../../components/Images/5.jpg';
import Image7 from '../../components/Images/6.jpg';
import Image8 from '../../components/Images/7.jpg';
import Image9 from '../../components/Images/8.jpg';
import Image10 from '../../components/Images/9.jpg';

export const products = [
  {
    id: 1,
    rating:  3.7,
    ratingCount: 590,
    title: "Smartphone",
    salary: 1000,
    category: "Electronics",
    description: "A high-end smartphone with the latest features and technology.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image3,
  },
  {
    id: 2,
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    description: "Noise-cancelling headphones with superior sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image4,
  },
  {
    id: 3,
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    description: "A powerful laptop for all your computing needs.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 4,
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    description: "A stylish smartwatch with multiple health tracking features.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 5,
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    description: "A versatile tablet perfect for work and play.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 6,
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    description: "A portable Bluetooth speaker with excellent sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 7,
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    description: "A high-resolution camera for capturing stunning photos.",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 8,
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    description: "A fast charger compatible with multiple devices.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 9,
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    description: "A high-definition monitor for an immersive viewing experience.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 10,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image9,
  },
  {
    id: 11,
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    description: "A high-end smartphone with the latest features and technology.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 12,
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    description: "Noise-cancelling headphones with superior sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 13,
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    description: "A powerful laptop for all your computing needs.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 14,
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    description: "A stylish smartwatch with multiple health tracking features.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 15,
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    description: "A versatile tablet perfect for work and play.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 16,
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    description: "A portable Bluetooth speaker with excellent sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 17,
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    description: "A high-resolution camera for capturing stunning photos.",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 18,
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    description: "A fast charger compatible with multiple devices.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 19,
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    description: "A high-definition monitor for an immersive viewing experience.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image4,
  },
  {
    id: 20,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 21,
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    description: "A high-end smartphone with the latest features and technology.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image6,
  },
  {
    id: 22,
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    description: "Noise-cancelling headphones with superior sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 23,
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    description: "A powerful laptop for all your computing needs.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image10,
  },
  {
    id: 24,
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    description: "A stylish smartwatch with multiple health tracking features.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 25,
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    description: "A versatile tablet perfect for work and play.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 26,
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 50,
    category: "Accessories",
    description: "A portable Bluetooth speaker with excellent sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 27,
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    description: "A high-resolution camera for capturing stunning photos.",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 28,
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 20,
    category: "Accessories",
    description: "A fast charger compatible with multiple devices.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 29,
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    description: "A high-definition monitor for an immersive viewing experience.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 30,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 31,
    rating: 5,
    ratingCount: 500,
    title: "Smartphone",
    salary: 150,
    category: "Electronics",
    description: "A high-end smartphone with the latest features and technology.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 32,
    rating: 4,
    ratingCount: 200,
    title: "Headphones",
    salary: 99,
    category: "Accessories",
    description: "Noise-cancelling headphones with superior sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 33,
    rating: 5,
    ratingCount: 300,
    title: "Laptop",
    salary: 1200,
    category: "Electronics",
    description: "A powerful laptop for all your computing needs.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image8,
  },
  {
    id: 34,
    rating: 4,
    ratingCount: 150,
    title: "Smartwatch",
    salary: 199,
    category: "Accessories",
    description: "A stylish smartwatch with multiple health tracking features.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 35,
    rating: 5,
    ratingCount: 400,
    title: "Tablet",
    salary: 300,
    category: "Electronics",
    description: "A versatile tablet perfect for work and play.",
    deliveryFee: 5,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image4,
  },
  {
    id: 36,
    rating: 4,
    ratingCount: 250,
    title: "Bluetooth Speaker",
    salary: 53,
    category: "Accessories",
    description: "A portable Bluetooth speaker with excellent sound quality.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image9,
  },
  {
    id: 37,
    rating: 5,
    ratingCount: 600,
    title: "Camera",
    salary: 800,
    category: "Electronics",
    description: "A high-resolution camera for capturing stunning photos.",
    deliveryFee: 15,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 38,
    rating: 4,
    ratingCount: 100,
    title: "Charger",
    salary: 30,
    category: "Accessories",
    description: "A fast charger compatible with multiple devices.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image3,
  },
  {
    id: 39,
    rating: 5,
    ratingCount: 350,
    title: "Monitor",
    salary: 250,
    category: "Electronics",
    description: "A high-definition monitor for an immersive viewing experience.",
    deliveryFee: 10,
    label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
    image: Image1,
  },
  {
    id: 40,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image7,
  },
  {
    id: 41,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 42,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image10,
  },
  {
    id: 43,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image4,
  },
  {
    id: 44,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image7,
  },
  {
    id: 45,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image9,
  },
  {
    id: 46,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image10,
  },
  {
    id: 47,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image9,
  },
  {
    id: 48,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image7,
  },
  {
    id: 49,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image2,
  },
  {
    id: 50,
    rating: 4,
    ratingCount: 180,
    title: "Keyboard",
    salary: 45,
    category: "Accessories",
    description: "A mechanical keyboard with customizable keys.",
    deliveryFee: 0,
    label: { text: "Limited Offer" },
    image: Image4,
  },
  

{
  id: 51,
  rating: 5,
  ratingCount: 450,
  title: "Gaming Console",
  salary: 500,
  category: "Electronics",
  description: "A next-gen gaming console with stunning graphics and performance.",
  deliveryFee: 20,
  label: { text: "New Arrival", bgcolor: "#00ff00", textcolor: "#000" },
  image: Image1,
},
{
  id: 52,
  rating: 4,
  ratingCount: 220,
  title: "Wireless Mouse",
  salary: 25,
  category: "Accessories",
  description: "A wireless mouse with ergonomic design and long battery life.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image2,
},
{
  id: 53,
  rating: 5,
  ratingCount: 320,
  title: "4K TV",
  salary: 800,
  category: "Electronics",
  description: "A 4K Ultra HD TV with vibrant colors and smart features.",
  deliveryFee: 30,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image1,
},
{
  id: 54,
  rating: 4,
  ratingCount: 180,
  title: "Fitness Tracker",
  salary: 60,
  category: "Accessories",
  description: "A fitness tracker with heart rate monitor and GPS.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image2,
},
{
  id: 55,
  rating: 5,
  ratingCount: 500,
  title: "Drone",
  salary: 1000,
  category: "Electronics",
  description: "A high-end drone with 4K camera and advanced features.",
  deliveryFee: 25,
  label: { text: "New Arrival", bgcolor: "#00ff00", textcolor: "#000" },
  image: Image1,
},
{
  id: 56,
  rating: 4,
  ratingCount: 150,
  title: "VR Headset",
  salary: 300,
  category: "Electronics",
  description: "A VR headset for an immersive virtual reality experience.",
  deliveryFee: 10,
  label: { text: "New Arrival", bgcolor: "#00ff00", textcolor: "#000" },
  image: Image1,
},
{
  id: 57,
  rating: 5,
  ratingCount: 400,
  title: "Smart Light Bulb",
  salary: 20,
  category: "Accessories",
  description: "A smart light bulb that can be controlled via smartphone.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image2,
},
{
  id: 58,
  rating: 4,
  ratingCount: 250,
  title: "Electric Scooter",
  salary: 500,
  category: "Electronics",
  description: "An electric scooter with long battery life and fast charging.",
  deliveryFee: 15,
  label: { text: "Limited Offer" },
  image: Image1,
},
{
  id: 59,
  rating: 5,
  ratingCount: 300,
  title: "Smart Thermostat",
  salary: 150,
  category: "Accessories",
  description: "A smart thermostat that can be controlled remotely.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image2,
},
{
  id: 60,
  rating: 4,
  ratingCount: 200,
  title: "E-Reader",
  salary: 120,
  category: "Electronics",
  description: "An e-reader with a high-resolution display and long battery life.",
  deliveryFee: 5,
  label: { text: "Limited Offer" },
  image: Image1,
},
{
  id: 61,
  rating: 5,
  ratingCount: 350,
  title: "Smart Doorbell",
  salary: 100,
  category: "Accessories",
  description: "A smart doorbell with video recording and motion detection.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image2,
},
{
  id: 62,
  rating: 4,
  ratingCount: 180,
  title: "Portable Projector",
  salary: 200,
  category: "Electronics",
  description: "A portable projector with high resolution and multiple connectivity options.",
  deliveryFee: 10,
  label: { text: "Limited Offer" },
  image: Image10,
},
{
  id: 63,
  rating: 5,
  ratingCount: 400,
  title: "Smart Lock",
  salary: 150,
  category: "Accessories",
  description: "A smart lock with keyless entry and remote access.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image2,
},
{
  id: 64,
  rating: 4,
  ratingCount: 220,
  title: "Wireless Earbuds",
  salary: 80,
  category: "Accessories",
  description: "Wireless earbuds with noise cancellation and long battery life.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image3,
},
{
  id: 65,
  rating: 5,
  ratingCount: 500,
  title: "Gaming Laptop",
  salary: 1500,
  category: "Electronics",
  description: "A high-performance gaming laptop with the latest graphics card.",
  deliveryFee: 20,
  label: { text: "New Arrival", bgcolor: "#00ff00", textcolor: "#000" },
  image: Image6,
},
{
  id: 66,
  rating: 4,
  ratingCount: 300,
  title: "Smart Speaker",
  salary: 100,
  category: "Accessories",
  description: "A smart speaker with voice assistant and high-quality sound.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image6,
},
{
  id: 67,
  rating: 5,
  ratingCount: 450,
  title: "Electric Toothbrush",
  salary: 50,
  category: "Accessories",
  description: "An electric toothbrush with multiple brushing modes.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image2,
},
{
  id: 68,
  rating: 4,
  ratingCount: 250,
  title: "Smart Plug",
  salary: 30,
  category: "Accessories",
  description: "A smart plug that can be controlled via smartphone.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image10,
},
{
  id: 69,
  rating: 5,
  ratingCount: 500,
  title: "Robot Vacuum",
  salary: 300,
  category: "Electronics",
  description: "A robot vacuum with smart navigation and powerful suction.",
  deliveryFee: 10,
  label: { text: "New Arrival", bgcolor: "#00ff00", textcolor: "#000" },
  image: Image1,
},
{
  id: 70,
  rating: 4,
  ratingCount: 200,
  title: "Smart Scale",
  salary: 40,
  category: "Accessories",
  description: "A smart scale that tracks weight and body composition.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image2,
},
{
  id: 71,
  rating: 5,
  ratingCount: 350,
  title: "Smart Glasses",
  salary: 250,
  category: "Accessories",
  description: "Smart glasses with augmented reality features.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image2,
},
{
  id: 72,
  rating: 4,
  ratingCount: 180,
  title: "Smart Coffee Maker",
  salary: 100,
  category: "Accessories",
  description: "A smart coffee maker with programmable settings.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image8,
},
{
  id: 73,
  rating: 5,
  ratingCount: 400,
  title: "Electric Kettle",
  salary: 60,
  category: "Accessories",
  description: "An electric kettle with temperature control.",
  deliveryFee: 0,
  label: { text: "Best Seller", bgcolor: "#ffd700", textcolor: "#000" },
  image: Image6,
},
{
  id: 74,
  rating: 4,
  ratingCount: 220,
  title: "Smart Mirror",
  salary: 200,
  category: "Accessories",
  description: "A smart mirror with built-in display and voice assistant.",
  deliveryFee: 0,
  label: { text: "Limited Offer" },
  image: Image5,
},
{
  id: 75,
  rating: 5,
  ratingCount: 500,
  title: "Smart Refrigerator",
  salary: 2000,
  category: "Electronics",
  description: "A smart refrigerator with touch screen and internet connectivity.",
  deliveryFee: 50,
  label: { text: "New Arrival", bgcolor: "#00ff00", textcolor: "#000" },
  image: Image3,
}
];